# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories=[
  {level1:"レディース",level1_children:[
              {level2:"トップス",level2_children:%W(
                Tシャツ/カットソー（半袖/袖なし）
                Tシャツ/カットソー（七分/長袖）
                シャツ/ブラウス（半袖/袖なし）
                シャツ/ブラウス（七分/長袖）
                ポロシャツ キャミソール タンクトップ
                ホルターネック
                ニット/セーター
                チュニック
                カーディガン/ボレロ
                アンサンブル
                ベスト/ジレ
                )},
              {level2:"ジャケット/アウター",level2_children: %W(
                テーラードジャケット
                ノーカラージャケット
                Gジャン/デニムジャケット
                レザージャケット
                ダウンジャケット
                ライダースジャケット
                ミリタリージャケット
                ダウンベスト
                ジャンパー/ブルゾン
                ポンチョ
                ロングコート
                トレンチコート
                ダッフルコート
                ピーコート
                )},
              {level2:"パンツ",level2_children: %W(
                すべて
                デニム/ジーンズ
                ショートパンツ
                カジュアルパンツ
                ハーフパンツ
                チノパン
                ワークパンツ/カーゴパンツ
                クロップドパンツ
                サロペット/オーバーオール
                オールインワン
                サルエルパンツ
                ガウチョパンツ
                その他
                )},
              {level2:"スカート",level2_children: %W(
                すべて
                ミニスカート
                ひざ丈スカート
                ロングスカート
                キュロット
                その他
                )},
              {level2:"ワンピース",level2_children:%W(
                すべて
                ミニワンピース
                ひざ丈ワンピース
                ロングワンピース
                その他
                )},
              {level2:"靴",level2_children:%W(
                すべて
                ハイヒール/パンプス
                ブーツ
                サンダル
                スニーカー
                ミュール
                モカシン
                ローファー/革靴
                フラットシューズ/バレエシューズ
                長靴/レインシューズ
                その他
                )},
              {level2:"ルームウェア/パジャマ",level2_children:%W(
                すべて
                パジャマ
                ルームウェア
                )},
              {level2:"レッグウェア",level2_children:%W(
                すべて
                ソックス
                スパッツ/レギンス
                ストッキング/タイツ
                レッグウォーマー
                その他
                )},
              {level2:"帽子",level2_children:%W(
                すべて
                ニットキャップ/ビーニー
                ハット
                ハンチング/ベレー帽
                キャップ
                キャスケット
                麦わら帽子
                その他
                )}
              ]},
  {level1:"メンズ",level1_children:[
              {level2:"トップス",level2_children:%W(
                Tシャツ/カットソー（半袖/袖なし）
                Tシャツ/カットソー（七分/長袖）
                シャツ
                ポロシャツ
                タンクトップ
                ニット/セーター
                パーカー
                カーディガン
                スウェット
                ジャージ
                ベスト
                その他
                )},
              {level2:"ジャケット/アウター",level2_children: %W(
                テーラードジャケット
                ノーカラージャケット
                Gジャン/デニムジャケット
                レザージャケット
                ダウンジャケット
                ライダースジャケット
                ミリタリージャケット
                ナイロンジャケット
                フライトジャケット
                ダッフルコート
                ピーコート
                ステンカラーコート
                トレンチコート
                モッズコート
                )},
              {level2:"パンツ",level2_children: %W(
                すべて
                デニム/ジーンズ
                ワークパンツ/カーゴパンツ
                スラックス
                チノパン
                ショートパンツ
                ペインターパンツ
                サルエルパンツ
                オーバーオール
                その他
                )},
              {level2:"靴",level2_children: %W(
                すべて
                スニーカー
                サンダル
                ブーツ
                モカシン
                ドレス/ビジネス
                長靴/レインシューズ
                デッキシューズ
                その他
                )},
              {level2:"バッグ",level2_children:%W(
                すべて
                ショルダーバッグ
                トートバッグ
                ボストンバッグ
                リュック/バックパック
                ウエストポーチ
                ボディーバッグ
                ドラムバッグ
                ビジネスバッグ
                トラベルバッグ
                メッセンジャーバッグ
                エコバッグ
                その他
                )},
              {level2:"スーツ",level2_children:%W(
                すべて
                スーツジャケット
                スーツベスト
                スラックス
                セットアップ
                その他
                )},
              {level2:"帽子",level2_children:%W(
                すべて
                キャップ
                ハット
                ニットキャップ/ビーニー
                ハンチング/ベレー帽
                キャスケット
                サンバイザー
                その他
                )},
              {level2:"アクセサリー",level2_children:%W(
                すべて
                ネックレス
                ブレスレット
                バングル/リストバンド
                リング
                ピアス（片耳用）
                ピアス（両耳用）
                アンクレット
                その他
                )},
              {level2:"小物",level2_children:%W(
                すべて
                長財布
                折り財布
                マネークリップ
                コインケース/小銭入れ
                名刺入れ/定期入れ
                キーケース
                キーホルダー
                ネクタイ
                手袋
                ハンカチ
                ベルト
                マフラー
                ストール
                )}
              ]}]


categories.each.with_index(1) do |category,i|
  level1_var="@category#{i}"
  level1_val= Category.create(name:"#{category[:level1]}")
  eval("#{level1_var} = level1_val")
    category[:level1_children].each.with_index(1) do |level1_child,j|
      level2_var="#{level1_var}_#{j}"
      level2_val= eval("#{level1_var}.children.create(name:level1_child[:level2])")
      eval("#{level2_var} = level2_val")
        level1_child[:level2_children].each do |level2_children_val|
          eval("#{level2_var}.children.create(name:level2_children_val)") 
        end
    end
end